#! /bin/bash -

# ENVIRONMENT VARIABLES
JAVAPATH=/usr/bin/java 
WEKA=lib/weka.jar

# ----------------------------------

COMMONS_CLI=./lib/commons-cli-1.0.jar
MRC=./lib/jmrc.jar

LIBS=.:$WEKA:$COMMONS_CLI:$MRC:bin/

${JAVAPATH} -Xmx512m -classpath $LIBS recognizer.PersonalityRecognizer $*



